/********************************************
*          dumped by: DvR3I PaFF            *
*********************************************/

#include "ui/menudef.h"
    itemDef
    {
        rect 472 415 336 20 1 1
        decoration
        visible 1
        forecolor 1 1 1 1
        textstyle 6
        textfont 4
        textalign 6
        textalignx -60
        textscale 0.15
        text "2024 - 2025, ^1CODZW 1.0.0.0"
    }