	#ifndef BACK_OPEN
	#define BACK_OPEN ;
	#endif
		itemDef
		{
			rect 56 448 528 40
			style 3
			foreColor 0.9 0.9 0.95 0.7
			background "black"
			decoration 
			visible 1
		}
		itemDef
		{
			rect 584 448 16 64
			style 3
			foreColor 0 0 0 0.7
			background "button_highlight_end"
			decoration 
			visible 1
		}
		itemDef
		{
			rect 40 448 -16 64
			style 3
			foreColor 0 0 0 0.7
			background "button_highlight_end"
			decoration 
			visible 1
		}
		itemDef
		{
			rect -120 464 160 32
			style 3
			foreColor 0.9 0.9 0.95 0.7
			background "black"
			decoration 
			visible 1
		}
		itemDef
		{
			rect 600 464 160 32
			style 3
			foreColor 0.9 0.9 0.95 0.7
			background "black"
			decoration 
			visible 1
		}