/********************************************
*          dumped by: DvR3I PaFF            *
*********************************************/

#include "ui/menudef.h"

	itemDef
	{
		name "windows"
		rect -50 -35 610 461 0 0
		style 1
		border 0
		ownerdraw 0
		ownerdrawFlag 0
		borderSize 1
		foreColor 1 1 1 1
		backColor 1 1 1 1
		background "black"
		outlineColor 0 0 0 0.5
		decoration 
		autoWrapped 
		type 0
		align 0
		textAlign 0
		textScale 0.5
		textStyle 3
		textFont 9
		feeder 0
		visible 1
	}
	itemDef
	{
		name "windows"
		rect -50 -35 610 461 0 0
		style 1
		border 0
		ownerdraw 0
		ownerdrawFlag 0
		borderSize 1
		foreColor 1 1 1 1
		backColor 1 1 1 1
		background "cardicon_cod4"
		outlineColor 0 0 0 0.5
		decoration
		autoWrapped
		type 0
		align 0
		textAlign 0
		textScale 0.5
		textStyle 3
		textFont 9
		feeder 0
		visible 1
    }