/********************************************
*          dumped by: DvR3I PaFF            *
*********************************************/

#include "ui/menudef.h"
	itemDef
	{
		rect 247 178 228 108 1 1
		style 1
		border 1
		ownerdraw 0
		ownerdrawFlag 0
		borderSize 1
		foreColor 1 1 1 1
		backColor 0 0 0 0.7
		borderColor 0.85 0.55 0 1
		outlineColor 0 0 0 0.5
		decoration 
		autoWrapped 
		type 0
		align 0
		textAlign 0
		textScale 0.5
		textStyle 3
		textFont 9
		feeder 0
		visible 1
		text ""
	}
	itemDef
	{
		rect 345 258 0 0 1 1
		decoration
		visible 1
		style 3
		forecolor 1 1 1 1
		textscale 0.5
		text "VS"
	}
	itemDef
	{
		rect 270 208 64 64 1 1
		decoration
		visible 1
		style 3
		forecolor 1 1 1 1
		textscale 0.5
		exp material ( dvarstring( "g_TeamIcon_Allies" ) )
	}
	itemDef
	{
		rect 380 208 64 64 1 1
		decoration
		visible 1
		style 3
		forecolor 1 1 1 1
		textscale 0.55
		exp material ( dvarstring( "g_TeamIcon_Axis" ) )
	}
	itemDef
	{
		name "team_choose_allies"
		rect 270 208 0 0 1 1
		decoration
		visible 1
		style 3
		forecolor 1 1 1 1
		textscale 0.55
		text "TF 141"
	}
	itemDef
	{
		name "team_choose_axis"
		rect 380 208 0 0 1 1
		decoration
		visible 1
		style 3
		forecolor 1 1 1 1
		textscale 0.55
		text "Spetsnaz"
	}
